services:
  Backend:
    image: backend-image
    build: ./Backend/CriptoApi
    container_name: Django-Backend
    ports:
      - "8001:8000"

  Frontend:
    image: frontend-image
    build: ./FrontEnd/cripto_front
    container_name: React-Frontend
    ports:
      - "3000:3000"
