version: '3.8'

services:
  backend:
    build:
      context: ./Backend/CriptoApi
      dockerfile: Dockerfile
    container_name: django-backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend/CriptoApi:/app
    environment:
      - DJANGO_SETTINGS_MODULE=CriptoApi.settings

  frontend:
    build:
      context: ./FrontEnd/cripto_front
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "5000:5000"
